Lambda-Emacs (𝛌-Emacs) is intended to serve as a useful starting point for your
own custom configuration. The design of this configuration is aimed at writing
and academic work in the humanities (for discussion of my view of the use of
text editors in the humanities [[https://www.colinmclear.net/posts/texteditor/][see here]]), rather than opposed to, e.g., a
programming language emphasis, though I've tried to make it user-friendly for
programmers as well. Another goal of 𝛌-Emacs is to provide enough commentary on
the configuration such that it might be useful to those new to emacs or even
[[https://en.wikipedia.org/wiki/Text_editor][text-editors]] generally.

*NOTE*: This repo is still very much a work in progress!! There may be breaking
changes so please update with that in mind. I am porting sections from [[https://github.com/mclear-tools/dotemacs][my own
config]], though this is a slow process.

* Why use 𝛌-Emacs?

Why choose this configuration over any of the other amazing Emacs "distros" out
there, such as (if you use vim-bindings) [[http://spacemacs.org][spacemacs]], or [[https://github.com/hlissner/doom-emacs][doom-emacs]], or the more
traditional configurations of [[Https://github.com/purcell/emacs.d][Purcell]], [[https://github.com/bbatsov/prelude][Batsov (prelude)]], [[https://github.com/seagle0128/.emacs.d][Zhang (Centaur Emacs)]],
the [[https://github.com/gilbertw1/bmacs][bmacs]] configuration of Bryan Gilbert (see also his [[https://github.com/gilbertw1/emacs-literate-starter][literate starter kit]]) and
[[https://github.com/novoid/dot-emacs][Karl Voit's]] config, John Kitchen's [[https://github.com/jkitchin/scimax][scimax]], Kieran Healy's [[https://github.com/kjhealy/emacs-starter-kit][social sciences
starter kit]], and [[https://github.com/caisah/emacs.dz][many others]]. Further helpful starts include [[https://github.com/hrs/sensible-defaults.el][sensible defaults]]
or especially [[https://github.com/SystemCrafters/rational-emacs][Rational Emacs]]. There are also the recent stylings of [[https://github.com/rougier][Nicolas
Rougier's]] [[https://github.com/rougier/elegant-emacs][elegant-emacs]] and [[https://github.com/rougier/nano-emacs][nano-emacs]]. Truly a surfeit of riches. So why
another one? Here are three reasons. 𝛌-Emacs is largely an abstraction from my
own config, which I wanted to make more easily available to others. I also want
a clean but useful config to point my students to. Finally, setting this up is a
useful way for me to think about how "best" to configure Emacs. 

* 𝛌-Emacs Features 

1. Short start up time -- emacs-init-time < 1 sec (though this may vary somewhat
   depending on your system)
2. Uses [[https://github.com/raxod502/straight.el][straight.el]] for package management
3. Comprehensive keybindings using [[https://github.com/jwiegley/use-package/blob/master/bind-key.el][bind-key]] 
4. Sensible defaults
5. Dired with sensible colors 
6. Completion with [[https://github.com/minad/vertico][Vertico]] and related packages
7. [[https://github.com/Lambda-Emacs/lambda-themes][Lambda-themes]], with toggles for dark/light mode & various other options
8. A custom status-line, [[https://github.com/Lambda-Emacs/lambda-line][Lambda-line]] 
9. Extensive MacOS integration
10. Single frame, tab-based, project workflow leveraging the built-in project.el
    and tab-bar, with [[https://github.com/mclear-tools/tabspaces][buffer-isolated tab/workspaces]]
11. A configurable splash page
12. A writing-centric configuration with great citation support, markdown, [[https://github.com/jgm/pandoc][pandoc]],
    dedicated functions for notes, and org-mode
   
* 𝛌-Emacs Modules

𝛌-Emacs is a "modular" distribution of Emacs. It consists of a set of "setup"
elisp files grouped according to the following areas (*NOTE*: these are still works in progress):

- *Core*: These files load essential libraries, useful functions, macros, and sane
  settings. 
- *UI*: Primary settings concerning frame, window, and buffer interaction, along
  with fonts, faces, themeing, completion, tabs/workspaces, and navigation all
  belong to this group.
- *Writing & Editing*: Settings for spelling, citation, dictionary, notes,
  typesetting (LaTeX) and writing-specific modes (markdown).
- *Org*: Writing, Project management, TODOs, Literate programming. What doesn't
  org do? Since many people use Emacs almost exclusively for org-mode, it
  warrants its own group. 
- *Programming & Languages*: Editing and Language specific settings. 
- *Shell*: Configuration for shell and command-line related settings. 
- *Project*: Version control settings and configuration for the built-in project.el


